version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock
    links:
      - zookeeper

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  timer-service:
    image: docker.artifacts.gtv-corp.net/gtv/timer-service:1-SNAPSHOT
    ports:
      - 8081:8080
    links:
      - kafka
      - zookeeper
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=6006
      SPRING_PROFILES_ACTIVE: cloudless
      KAFKA: kafka
      ZOOKEEPER: zookeeper