spring:
  application:
      name: timerservice
  cloud:
    stream:
      default:
        content-type: application/json
        group: timerservice

server:
  port: 8080

management:
  port: 8090
  security:
    enabled: false

timerservice:
  eventtimer:
    duration: 20m
    tickslice: 20
